import { UiTexts, LanguageKeywords } from './types';

export const GEMINI_FLASH_MODEL = 'gemini-2.5-flash-preview-04-17';
export const FIXED_INTERACTION_LANGUAGE = 'español'; // Application will use Spanish

export const BASE_UI_TEXTS: UiTexts = {
  appTitle: "V Compresión Lectora",
  tabContentTools: "Contenido y Herramientas",
  tabPractice: "Práctica Guiada",
  tabReport: "Informe y reinicio",
  contentToolsTitle: "Configuración y Carga de Contenido",
  courseLabel: "Curso:", 
  // interactionLanguageLabel: "Idioma de interacción con la IA:", // Removed
  // interactionLanguagePlaceholder: "ej. español, catalán", // Removed
  // translateInterfaceButton: "Traducir también la interfaz (opcional)", // Removed
  // translatingInterfaceButton: "Traduciendo Interfaz...", // Removed
  inputMethodDocTitle: "Opción 1: Cargar un Documento",
  loadDocumentLabel: "Archivo (PDF, TXT, MD, DOCX):",
  dropDocumentPlaceholder: "Arrastra y suelta un documento aquí, o haz clic para seleccionar.",
  inputMethodTextTitle: "Opción 2: Pegar Texto Directamente",
  pasteTextLabel: "Contenido Textual:",
  pasteTextPlaceholder: "Pega aquí tu material de estudio... (El contenido de un documento cargado también aparecerá aquí)",
  inputMethodImageTitle: "Opción 3: Cargar una Imagen",
  loadImageLabel: "Archivo de Imagen:",
  dropImagePlaceholder: "Arrastra y suelta una imagen aquí, o haz clic para seleccionar.",
  documentLoadedMsg: "Documento cargado.",
  imageErrorPlaceholder: "Error Imagen",
  canLoadTextAndImage: "Puedes usar un documento o texto pegado, y complementarlo con una imagen si lo deseas.",
  guidedPracticeTitle: "Práctica Guiada",
  questionTypeLabel: "Tipo de Pregunta:",
  studyModeLabel: "Modo de Estudio:",
  generateQuestionButton: "Generar Nueva Pregunta",
  generatingQuestionButton: "Generando...",
  yourAnswerLabel: "Tu Respuesta:",
  yourAnswerPlaceholder: "Escribe tu respuesta aquí...",
  checkAnswerButton: "Comprobar Respuesta",
  evaluatingButton: "Evaluando...",
  explainMoreButton: "✨ Explicar más",
  explainingButton: "Explicando...",
  createAnalogiesButton: "✨ Crear Analogías",
  creatingAnalogiesButton: "Creando Analogías...",
  correctLabel: "Correctas:",
  incorrectLabel: "Incorrectas:",
  reportTitle: "Informe y reinicio",
  generateReportButton: "Generar/Actualizar Informe",
  generatingReportButton: "Generando Informe...",
  copyReportButton: "Copiar Informe",
  reportResultsTitle: "Informe de Resultados:",
  studySuggestionsTitle: "Sugerencias de Estudio:",
  clickToGenerateReportMsg: "Haz clic en el botón de arriba para generar tu informe.",
  completeQuestionsForReportMsg: "Completa algunas preguntas en la pestaña \"Práctica Guiada\" para poder generar un informe.",
  restartSessionButton: "Reiniciar Sesión",
  descriptionModalTitle: "🚀 Compresión Lectora", // Updated to match new app name context
  closeButton: "Cerrar",
  confirmRestartMsg: "¿Estás seguro de que quieres reiniciar la sesión? Se borrará el progreso actual, pero la configuración (curso, etc.) se mantendrá.",
  yesRestartButton: "Sí, reiniciar",
  cancelButton: "Cancelar",
  acceptButton: "Aceptar",
  summaryModalTitle: "✨ Resumen del Contenido",
  copySummaryButton: "Copiar Resumen",
  faqModalTitle: "✨ Preguntas Frecuentes",
  copyFaqButton: "Copiar FAQs",
  elaborationModalTitle: "✨ Explicación Detallada",
  elaborationModalConceptLabel: "Sobre:",
  copyElaborationButton: "Copiar Explicación",
  analogyModalTitle: "✨ Analogías para Entender Mejor",
  copyAnalogiesButton: "Copiar Analogías",
  flashcardsModalTitle: "✨ Flashcards",
  flashcardOf: "Flashcard {current} de {total}",
  prevFlashcardButton: "Anterior",
  shuffleFlashcardButton: "Barajar",
  nextFlashcardButton: "Siguiente",
  closeFlashcardsButton: "Cerrar Flashcards",
  semanticMapModalTitle: "✨ Mapa Conceptual Interactivo",
  downloadHtmlButton: "Descargar HTML",
  descP1: "¡Bienvenido/a al Asistente de Compresión Lectora! Esta herramienta está diseñada para ayudarte a <strong>comprender y repasar cualquier material de estudio</strong> de una forma interactiva y eficaz.",
  descP2: "Para poderlo utilizar es necesario haber iniciado sesión en una cuenta de Google que permita el uso de Gemini.",
  descP3: "Simplemente carga tu contenido (texto, PDF, DOCX o imágenes) y deja que la IA te guíe.",
  descTitle2: "¿Para qué sirve?",
  descP4: "El objetivo principal es transformar tu material de estudio en una experiencia de aprendizaje activa. En lugar de solo leer, podrás:",
  descL1I1: "✅ Poner a prueba tu comprensión con preguntas generadas por IA.",
  descL1I2: "🗺️ Visualizar conceptos clave y sus relaciones con <strong>Mapas Conceptuales</strong> interactivos (descargables en HTML). (Funcionalidad accesible programáticamente, botón de UI eliminado)",
  descL1I3: "🔍 Profundizar en conceptos clave con explicaciones detalladas y analogías.",
  descL1I4: "💬 Conversar con la IA sobre el contenido para aclarar dudas (la IA responderá en español).",
  descL1I5: "📊 Obtener un resumen de tu rendimiento y sugerencias para mejorar.",
  descL1I6: "🛠️ Utilizar herramientas como resúmenes automáticos, FAQs y flashcards. (Funcionalidades accesibles programáticamente, botones de UI eliminados)",
  descTitle3: "¿Cómo se utiliza?",
  descP5: "La aplicación se organiza en tres pestañas principales:",
  descTab1Name: "Contenido y Herramientas",
  descTab1P1: "Aquí es donde todo comienza:",
  descTab1L1I1: "<strong>Configuración Inicial:</strong> Ajusta tu curso. La aplicación y la IA interactuarán en español.",
  descTab1L1I2: "<strong>Carga de Contenido:</strong> Sube tus materiales de estudio. Puedes cargar un documento (PDF, TXT, MD, DOCX), pegar texto directamente, o subir una imagen. Puedes combinar texto con una imagen.",
  descTab1L1I3: "<strong>Herramientas de Análisis:</strong> (Los botones para estas herramientas han sido eliminados de la interfaz principal. Las funcionalidades como Resumir, FAQ, Flashcards y Mapa Conceptual permanecen en el código para posible reintegración o acceso programático).",
  descTab1L2I1: "✨ <strong>Resumir:</strong> Obtén un resumen conciso del material.",
  descTab1L2I2: "✨ <strong>FAQ:</strong> Genera una lista de preguntas frecuentes con sus respuestas.",
  descTab1L2I3: "✨ <strong>Flashcards:</strong> Crea tarjetas de estudio interactivas.",
  descTab1L2I4: "✨ <strong>Mapa Conceptual:</strong> Visualiza los conceptos clave y sus relaciones en un mapa interactivo (descargable).",
  descTab2Name: "Práctica Guiada",
  descTab2P1: "Pon a prueba tu conocimiento:",
  descTab2L1I1: "<strong>Selecciona el Tipo de Pregunta:</strong> Elige entre varios formatos (general, definición, relación, aplicación, V/F, opción múltiple) o deja que la IA elija aleatoriamente.",
  descTab2L1I2: "<strong>Modo de Estudio:</strong> Escoge 'Aleatorio' para preguntas variadas o 'Guiado' para un aprendizaje progresivo sobre conceptos del material.",
  descTab2L1I3: "<strong>Genera y Responde:</strong> Pide una pregunta, escribe tu respuesta y compruébala. La IA te dará feedback.",
  descTab2L1I4: "<strong>Profundiza:</strong> Si tienes dudas, usa 'Explicar más' o 'Crear Analogías' sobre la pregunta o concepto actual.",
  descTab2L1I5: "<strong>Seguimiento:</strong> Tus aciertos y errores se registran para el informe final.",
  descTab3Name: "Informe y Reinicio",
  descTab3P1: "Revisa tu progreso y gestiona la sesión:",
  descTab3L1I1: "<strong>Generar Informe:</strong> Obtén un resumen de tu rendimiento, incluyendo puntos fuertes, débiles y sugerencias de estudio personalizadas.",
  descTab3L1I2: "<strong>Reiniciar Sesión:</strong> Borra el progreso actual (preguntas, respuestas, informe) para empezar de nuevo. La configuración de curso se mantiene.", 
  descTab4Name: "Consejos Adicionales",
  descTab4P1: "Para sacar el máximo provecho:",
  descTab4L1I1: "<strong>Contenido Claro:</strong> Cuanto más claro y estructurado sea tu material de estudio, mejores serán los resultados de la IA.",
  descTab4L1I2: "<strong>Experimenta:</strong> Prueba diferentes tipos de preguntas y modos de estudio para ver qué funciona mejor para ti.",
  descP6: "¡Esperamos que esta herramienta te sea de gran utilidad en tus estudios!",
  imageLoadedToast: 'Imagen "{fileName}" cargada.',
  docLoadedToast: 'Documento "{fileName}" cargado y procesado.',
  pdfLibNotLoadedToast: 'La librería de PDF aún no está cargada. Por favor, espera e inténtalo de nuevo.',
  visNotLoadedToast: 'La librería para mapas conceptuales aún no está cargada. Por favor, espera e inténtalo de nuevo.',
  mammothNotLoadedToast: 'La librería para DOCX aún no está cargada. Por favor, espera e inténtalo de nuevo.',
  noContentToGenerateToast: "Por favor, carga algún contenido (texto o imagen) antes de generar una pregunta.",
  noContentForActionToast: "Por favor, carga algún contenido (texto o imagen) antes de realizar esta acción.",
  questionTypeRandomToast: "Tipo de pregunta aleatoria: {type}",
  noQuestionToEvaluateToast: "Por favor, genera una pregunta y proporciona una respuesta antes de evaluar.",
  noHistoryForReportToast: "No hay historial de sesión para generar un informe.",
  noConceptToElaborateToast: "No hay un concepto o pregunta seleccionada para elaborar.",
  noContentForElaborationToast: "Carga contenido para tener contexto para la elaboración.",
  noConceptForAnalogiesToast: "No hay un concepto o pregunta seleccionada para generar analogías.",
  noContentForAnalogiesToast: "Carga contenido para tener contexto para las analogías.",
  invalidFlashcardsToast: "La IA no devolvió flashcards válidas. Inténtalo de nuevo.",
  errorProcessingFlashcardsToast: "Error al procesar las flashcards recibidas de la IA.",
  noSemanticMapDataToast: "La IA no devolvió datos válidos para el mapa conceptual. Inténtalo de nuevo.",
  errorProcessingSemanticMapToast: "Error al procesar los datos del mapa conceptual recibidos de la IA.",
  sessionRestartedToast: "Sesión reiniciada. La configuración de tipo de pregunta, modo de estudio y curso se mantienen (excepto tipo de pregunta que vuelve a Aleatorio).",
  copiedToClipboardSuccess: "{item} copiado(s) al portapapeles!",
  copiedToClipboardFallback: "{item} copiado(s)! (fallback)",
  copiedToClipboardError: "No se pudo copiar el/la {item}.",
  copiedToClipboardErrorFallback: "Error al copiar el/la {item} (fallback).",
  noItemToCopy: "No hay {item} para copiar.",
  // interfaceTranslationSuccess: "Interfaz traducida a {language}.", // Removed
  // interfaceTranslationError: "Error al traducir la interfaz.", // Removed
  describingImageForMapToast: "Describiendo imagen para el mapa conceptual...",
  imageDescriptionSuccessToast: "Imagen descrita. Generando mapa conceptual...",
  imageDescriptionErrorToast: "Error al describir la imagen para el mapa conceptual.",
  qTypeRandom: "Aleatorio",
  qTypeGeneral: "General",
  qTypeDefinition: "Definición",
  qTypeRelationship: "Relación entre conceptos",
  qTypeApplication: "Aplicación/Ejemplo",
  qTypeTrueFalse: "Verdadero/Falso",
  qTypeMultipleChoice: "Opción Múltiple",
  studyModeRandom: "Aleatorio",
  studyModeGuided: "Guiado (progresivo)",
  focusModeButtonLabel: "Pantalla Completa", 
  exitFocusModeButtonLabel: "Salir de Pantalla Completa", 
  focusModeActiveToast: "Pantalla completa activada.", 
  focusModeInactiveToast: "Pantalla completa desactivada.", 
  focusModeRequestErrorToast: "No es posible maximizar la aplicación en este navegador.",
};

export const LANGUAGE_KEYWORDS: LanguageKeywords = {
  'español': { correct: 'CORRECTO', incorrect: 'INCORRECTO' },
  'catalan': { correct: 'CORRECTE', incorrect: 'INCORRECTE' }, // Kept for potential internal use, though UI doesn't allow changing
  'english': { correct: 'CORRECT', incorrect: 'INCORRECT' },   // Kept for potential internal use
};

// DEFAULT_INTERACTION_LANGUAGE is now FIXED_INTERACTION_LANGUAGE
export const COURSE_OPTIONS = ["1º ESO", "2º ESO", "3º ESO", "4º ESO", "Bachillerato"];